### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by Defman** [feather-rs/lieutenant#1]
1. Dispatchers should provide an iterator over all executable nodes. It's not effective to iterate over slab and such we might just want to drop it and take the cost rearranging the Vec when deleting command nodes.
2. Executable commands/nodes should have their usage and description associated to allow for help/man generation.
3. ArgumentParsers and -Checker should take the entirety of the unparsed input and consume the whats required for parsing. Such to allow for `QuotedStringParser`, `remainingStringParser`, and `PositionParser` ("/tp <destination: x y z>") .
4. Enum support, the current definition of usage does not support `(a|b|c)` however it may be treated as `<enum>` and the usage derived from the type instead.
5. Maybe we should drop usage from `#[command(usage)]` an base the routing purely on the function signature? Ie having `fn command(_: Literal<{"tp"}>, location: BlockPosition)`, however, would require const generics to be stabilized.
6. Some automated static collection of commands like inventory. Such that you don't have to call `Dispatcher::register` for each command. However, it would prevent multiple different command dispatchers from existing. Which might be useful to provide different commands based on worlds or similar.
7. How do we determine the best match of an input? Would it be the command which are closes to the leaves, or the path which has the highest dept? Both of these options would ofc require no ambiguity, ie only one executable node exist in the remaining tree.

**Comment by Defman** [comment]
Maybe we want to build the command dispatcher from `Vec<CommandSpec>` such that we can base help from `Vec<CommandSpec>` instead of the dispatcher. However, these two may come out of sync if commands are added or removed from either.
```rust
struct State {
  commands: Vec<CommandSpec>
}
// Over
struct State {
  commands: Rc<CommandDispatcher>,
}
```
Since the second one would require `Rc`.

```rust
#[test]
fn help_command() {
    use std::borrow::Cow;
    use std::rc::Rc;
    struct State {
        pub dispatcher: Rc<CommandDispatcher<Self>>,
        pub usages: Vec<Cow<'static, str>>,
        pub descriptions: Vec<Cow<'static, str>>,
    }

    let mut dispatcher = CommandDispatcher::new();

    #[command(
        usage = "/help <page>",
        description = "Shows the descriptions and usages of all commands."
    )]
    fn help(state: &mut State, page: u32) {
        state.usages = state
            .dispatcher
            .command_meta()
            .skip(page as usize * 10)
            .take(10)
            .map(|meta| meta.usage.clone())
            .collect();
        state.descriptions = state
            .dispatcher
            .command_meta()
            .skip(page as usize * 10)
            .take(10)
            .filter_map(|meta| meta.description.clone())
            .collect();
    }

    dispatcher.register(help).unwrap();

    let dispatcher = Rc::new(dispatcher);

    let mut ctx = State {
        dispatcher: Rc::clone(&dispatcher),
        usages: vec![],
        descriptions: vec![],
    };

    assert!(dispatcher.dispatch(&mut ctx, "help 0"));
    assert_eq!(ctx.usages, vec!["/help <page>"]);
    assert_eq!(ctx.descriptions, vec!["Shows the descriptions and usages of all commands."]);

    assert!(dispatcher.dispatch(&mut ctx, "help 1"));
    assert!(ctx.usages.is_empty());
    assert!(ctx.descriptions.is_empty());
}

```

**Comment by Defman** [comment]
Commands should also have a concept of priority/weight since some parsers might overlap. However, I dont know how we should handle merging of parsers / arguments.

**Comment by caelunshun** [comment]
> 6. Some automated static collection of commands like inventory. Such that you don't have to call `Dispatcher::register` for each command. However, it would prevent multiple different command dispatchers from existing. Which might be useful to provide different commands based on worlds or similar.

Unfortunately, `inventory` has a bunch of bugs which cause things randomly not to get registered, so I'm afraid we won't be able to do this.

**Comment by Defman** [comment]
All of the above should be resolve by #2
