### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by Defman** [feather-rs/lieutenant#3]
The following trait should be async
- `ArgumentParser`
- `ArgumentChecker`
- `ArgumentSuggester`

Dispatching of commands should be async as well.

**Comment by caelunshun** [comment]
One issue is that traits do not yet support `async fn`s, which is going to make this a whole lot more difficult.

**Comment by Redrield** [comment]
Would [async-trait](https://crates.io/crates/async-trait) work as a stop-gap to let this move forward, and then remove it in future when `async fn` in traits is accepted?

**Comment by Defman** [comment]
#2 Resolves this issue
